init:
  - git config --global core.autocrlf input

build: 'off'

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm i -g npm
  - npm i

test_script:
  - node --version
  - npm --version
  - cmd: npm run lint && npm t

environment:
  matrix:
    - nodejs_version: 'stable'
    - nodejs_version: '12'
    - nodejs_version: '10'
